name: example
description: A example of pedantic_kiri.
version: 1.0.0
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  meta: any
  pedantic: any
  pedantic_kiri:
    path: ..
