name: pedantic_kiri
description: "[kiri edition] How to get the most value from Dart static analysis."
version: 0.0.1
author: kiri
homepage: https://github.com/keisuke-kiriyama/pedantic_kiri

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
